-- Add up migration script here
CREATE TABLE IF NOT EXISTS orderevent (
    id SERIAL PRIMARY KEY,
    exchange VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    type_ VARCHAR NOT NULL,
    symbol VARCHAR NOT NULL,
    side VARCHAR NOT NULL,
    order_type VARCHAR NOT NULL,
    fee_type VARCHAR,
    liquidity VARCHAR,
    price VARCHAR,
    order_id VARCHAR NOT NULL,
    client_oid VARCHAR NOT NULL,
    trade_id VARCHAR,
    origin_size VARCHAR,
    size VARCHAR,
    filled_size VARCHAR,
    match_size VARCHAR,
    match_price VARCHAR,
    canceled_size VARCHAR,
    old_size VARCHAR,
    remain_size VARCHAR,
    remain_funds VARCHAR,
    order_time BIGINT NOT NULL,
    ts BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
