CREATE TABLE IF NOT EXISTS orderactive (
    id SERIAL PRIMARY KEY,
    exchange VARCHAR NOT NULL,
    order_id VARCHAR NOT NULL,
    symbol VARCHAR NOT NULL,
    side VARCHAR NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
