-- Add down migration script here
ALTER TABLE ticker ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), ADD COLUMN buy VARCHAR(50), ADD COLUMN best_bid_size VARCHAR(50), ADD COLUMN sell VARCHAR(50), ADD COLUMN best_ask_size VARCHAR(50), ADD COLUMN change_rate VARCHAR(50), ADD COLUMN change_price VARCHAR(50), ADD COLUMN high VARCHAR(50), ADD COLUMN low VARCHAR(50), ADD COLUMN vol VARCHAR(50), ADD COLUMN vol_value VARCHAR(50), ADD COLUMN last VARCHAR(50), ADD COLUMN average_price VARCHAR(50);

