-- Add up migration script here
CREATE TABLE Symbol (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    symbol VARCHAR(50),
    name VARCHAR(100),
    base_currency VARCHAR(50),
    quote_currency VARCHAR(50),
    fee_currency VARCHAR(50),
    market VARCHAR(50),
    base_min_size VARCHAR(50),
    quote_min_size VARCHAR(50),
    base_max_size VARCHAR(50),
    quote_max_size VARCHAR(50),
    base_increment VARCHAR(50),
    quote_increment VARCHAR(50),
    price_increment VARCHAR(50),
    price_limit_rate VARCHAR(50),
    min_funds VARCHAR(50),
    is_margin_enabled BOOLEAN,
    enable_trading BOOLEAN,
    fee_category SMALLINT,
    maker_fee_coefficient VARCHAR(50),
    taker_fee_coefficient VARCHAR(50),
    st BOOLEAN,
    callauction_is_enabled BOOLEAN,
    callauction_price_floor VARCHAR(50),
    callauction_price_ceiling VARCHAR(50),
    callauction_first_stage_start_time BIGINT,
    callauction_second_stage_start_time BIGINT,
    callauction_third_stage_start_time BIGINT,
    trading_start_time BIGINT
)
