-- Add up migration script here
CREATE TABLE IF NOT EXISTS orderactive (
  id SERIAL PRIMARY KEY,
  exchange VARCHAR NOT NULL,
  order_id VARCHAR NOT NULL,
  symbol VARCHAR NOT NULL,
  side VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
